version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: backendDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "7040:7040"
    depends_on:
      - db
    environment:
    
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=backendDb;Username=postgres;Password=password;Port=5432

volumes:
  db_data:
